### ISSUE TITLE
consider adding azure tests

### ISSUE THREAD

**Issue by cgwalters** [virt-s1/bootc-workflow-test#195]
Now that https://github.com/containers/bootc/issues/175 is fixed I think we could add an Azure `install to-existing-root` test there right?

**Comment by shi2wei3** [comment]
Yes, it's in our plan. Since we don't want to regularly upload azure images for bootc install test use case, so we want to cover the azure platform with bib only. And bib haven't enable azure for now. This is also what I want to ask, does the plan is to enable azure for bib "recently"? If not, we won't pending on bib for testing on azure.

**Comment by cgwalters** [comment]
> Since we don't want to regularly upload azure images for bootc install test use case, so we want to cover the azure platform with bib only. 

Hmm, I was thinking the opposite; using the stock RHEL Azure images with a `bootc install to-existing-root` flow.
